apiVersion: batch/v1
kind: Job
metadata:
  name: database-configuration
  namespace: db2
spec:
  template:
    spec:
      serviceAccountName: db2-configure-sa
      containers:
      - name: db-config
        image: quay.io/langley_millard_ibm/dbs_configure # location the image is pushed to i.e. quay.io/langley_millard_ibm/repo_name
        command: ["./create_db.sh"]
        env:
        - name: USER_LIST
          value: "gcd,fpos,ros,icndb,os1"
        - name: KUBECONFIG
          value: "/tmp/config"
        args: ["-i", "BAN,FNCM,IER"]
        imagePullPolicy: Always
      restartPolicy: OnFailure
  backoffLimit: 2
  # path to preconfigure job git repo https://github.com/oto-cp4ba-gitops/cp4ba-config-jobs
  # branch is origin/feature/multi-db-init-mn