apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: get-cert-ingress-rb
  namespace: default
subjects:
- kind: ServiceAccount
  name: cp4ba-sa
roleRef:
  kind: ClusterRole 
  name: get-cert-ingress
  apiGroup: rbac.authorization.k8s.io